### ISSUE TITLE
Can we get a new release for crates.io?

### ISSUE THREAD

**Issue by marschattha** [fwcd/tree-sitter-kotlin#112]
Can we bundle current code into a new release?

And an update to the web sample https://fwcd.dev/tree-sitter-kotlin/ would also be very much appreciated.

**Comment by K1rakishou** [comment]
After the latest update the playground is broken. Please update it too.

**Comment by fwcd** [comment]
0.3.3 is now released. Note that #106 was reverted, because the parser got too large. The web version will be updated too, please be patient...

**Comment by K1rakishou** [comment]
Thanks.
