### ISSUE TITLE
feature: release a new tree-sitter 0.21.0 compatible release

### ISSUE THREAD

**Issue by HerringtonDarkholme** [fwcd/tree-sitter-kotlin#118]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

ast-grep is using a lot of tree-sitter grammars and is going to upgrading the tree-sitter parser library.

However, tree-sitter-kotlin dependency range is blocking the upgrade.

e.g.
https://github.com/ast-grep/ast-grep/issues/1057

### Describe the solution you'd like

Release a new tree-sitter 0.21 compatible version

### Describe alternatives you've considered

Make the dependency more compatible by relaxing the version range

**Comment by HerringtonDarkholme** [comment]
I noticed that the current new package will break 0.21 tree-sitter since the version specified is 0.22

https://github.com/fwcd/tree-sitter-kotlin/blob/eca05edbab1918d7d36a0d30d086ba7b6b1e8803/Cargo.toml#L24

**Comment by fwcd** [comment]
0.3.6 is released and should support 0.21
