### ISSUE TITLE
Refactor external scanner to use `tree_sitter/array.h`

### ISSUE THREAD

**Issue by fwcd** [fwcd/tree-sitter-kotlin#131]
Tree-sitter now ships an official dynamic array that could replace our own `Stack` implementation: https://tree-sitter.github.io/tree-sitter/creating-parsers

**Comment by ObserverOfTime** [comment]
I already did that in #115 4.5 months ago. :)

**Comment by fwcd** [comment]
Ah sorry for not seeing this, somehow got lost in the stack of other PRs. Thanks, I'll have look soon!
