### ISSUE TITLE
Commit rights on tree-sitter-kotlin

### ISSUE THREAD

**Issue by aryx** [fwcd/tree-sitter-kotlin#19]
Hi @fwcd 

I am the original author of semgrep and we are considering using your tree-sitter-kotlin for adding support for Kotlin in Semgrep.
We have a few extensions to tree-sitter-kotlin that improve the parsing rate from 70% to 90% on the top 20 github kotlin projects.
Looking at the recent activity on this repository, there are a few people like @gzsombor that made PR that didn't get review or merged. Would you mind give more commit rights to external contributors to accelerate the development of tree-sitter-kotlin?

**Comment by fwcd** [comment]
Hi, glad you're finding this project useful! I haven't really had much time to maintain it recently, but I would be happy to grant other contributors commit access, as long as they follow the general style of the project and add tests.

**Comment by aryx** [comment]
sounds great! Thx a lot.

**Comment by gzsombor** [comment]
Having published to crates.io would also nice be :wink:
