### ISSUE TITLE
newline in method chain calls leads to parsing errors

### ISSUE THREAD

**Issue by aryx** [fwcd/tree-sitter-kotlin#32]
On this simple example:
```
bar.foo()
     .show()
```
tree-sitter will parse as
```
(source_file [0, 0] - [2, 0]
  (call_expression [0, 0] - [0, 9]
    (navigation_expression [0, 0] - [0, 7]
      (simple_identifier [0, 0] - [0, 3])
      (navigation_suffix [0, 3] - [0, 7]
        (simple_identifier [0, 4] - [0, 7])))
    (call_suffix [0, 7] - [0, 9]
      (value_arguments [0, 7] - [0, 9])))
  (ERROR [1, 3] - [1, 4])
  (call_expression [1, 4] - [1, 9]
    (simple_identifier [1, 4] - [1, 7])
    (call_suffix [1, 7] - [1, 9]
      (value_arguments [1, 7] - [1, 9]))))
test.kt	0 ms	(ERROR [1, 3] - [1, 4])
```
This is because newlines (parsed as 'semi' in the grammar) are not allowed in navigation expressions.

Originally discussed here: https://github.com/fwcd/tree-sitter-kotlin/pull/25

**Comment by aryx** [comment]
grammar.js has both:
```
  extras: $ => [
    $.comment,
    /\s+/ // Whitespace
  ],
```
so I guess \n is accepted by \s,
but then it also has
```
    // See also https://github.com/tree-sitter/tree-sitter/issues/160
    // generic EOF/newline token
    _semi: $ => /[\r\n]+/,

    _semis: $ => /[\r\n]+/,
```
which also accepts \n, so why one win? when a semi is inserted and when it is treated as an extras: which is skipped?
(BTW @fwcd why both _semi and _semis? they seem identical).

**Comment by aryx** [comment]
cc @colleend

**Comment by aryx** [comment]
Is it because of the context-aware lexing @maxbrunsfeld? In function calls there are no _semis expected, so the context-aware
lexing will parsed the newline as a comment, but in `o.foo() NEWLINE .bar()` a semicolon is possible according to the grammar at that point, in which case _semis will be produced?

Is there a way to extend the grammar to not get those NEWLINE when the token after is a dot?

**Comment by aryx** [comment]
Ok I followed what @maxbrunsfeld said and imitated what tree-sitter-javascript does and I manage to get to 98.6% correct parsing on a big corpus of Kotlin code! Woohoo. PR will come soon.
This context-aware lexing is really powerful BTW @maxbrunsfeld. This is really unique to tree-sitter.

**Comment by maxbrunsfeld** [comment]
@aryx That's great to hear!
