### ISSUE TITLE
Parse variable in side "" string

### ISSUE THREAD

**Issue by haphamdev** [fwcd/tree-sitter-kotlin#59]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/6322508/193729723-8c3798cb-5c92-42f9-ab2a-7fb64791d506.png">
`$companyId` is not recognized as variable in the above image.

**Comment by ObserverOfTime** [comment]
This has been fixed.

**Comment by VladimirMakaev** [comment]
verified this is fixed. closing
