### ISSUE TITLE
Investigate why the WASM binary no longer works in the playground

### ISSUE THREAD

**Issue by fwcd** [fwcd/tree-sitter-kotlin#98]
For some reason, the 0.3.0 WASM binary built for the web playground (2b27f2974449d02b82c1073a90ec593a4953c57f) seems to run into an error:

```
RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
    re https://fwcd.dev/tree-sitter-kotlin/tree-sitter.js:1
    N https://fwcd.dev/tree-sitter-kotlin/tree-sitter.js:1
    pe https://fwcd.dev/tree-sitter-kotlin/tree-sitter.js:1
    Se https://fwcd.dev/tree-sitter-kotlin/tree-sitter.js:1
    load https://fwcd.dev/tree-sitter-kotlin/tree-sitter.js:1
    promise callback*load https://fwcd.dev/tree-sitter-kotlin/tree-sitter.js:1
    handleLanguageChange https://fwcd.dev/tree-sitter-kotlin/playground.js:89
    <anonymous> https://fwcd.dev/tree-sitter-kotlin/playground.js:79
    async* https://fwcd.dev/tree-sitter-kotlin/playground.js:462
[playground.js:91:17](https://fwcd.dev/tree-sitter-kotlin/playground.js)
    handleLanguageChange https://fwcd.dev/tree-sitter-kotlin/playground.js:91
    <anonymous> https://fwcd.dev/tree-sitter-kotlin/playground.js:79
    <anonymous> https://fwcd.dev/tree-sitter-kotlin/playground.js:462
```

Possible causes would be the introduction of the new scanner or an issue with Emscripten. There seem to be [quite a few upstream reports](https://github.com/tree-sitter/tree-sitter/issues?q=Assertion+failed%3A+undefined) of similar issues. Just to mention a few:

- https://github.com/tree-sitter/tree-sitter/issues/1652
- https://github.com/tree-sitter/tree-sitter/issues/398
- https://github.com/tree-sitter/tree-sitter/issues/1560
- https://github.com/tree-sitter/tree-sitter/issues/1593
- https://github.com/tree-sitter/tree-sitter/issues/1300

> Note: Browsers like Firefox seem to cache the WASM binary pretty aggressively, so disabling the HTTP Cache in the devtools is recommended for development.

As a temporary workaround, the [playground](https://fwcd.github.io/tree-sitter-kotlin) will keep using 0.2.11 until we've fixed this (5af36d3ea561ff83010af99ddb0838f4ee7b605c).

**Comment by VladimirMakaev** [comment]
@fwcd The binary built from current sources works fine. It just needs to be built with correct version of emscripten. 
This worked for me:
```
emsdk install 2.0.17 && emsdk activate 2.0.17
``` 
More info here https://github.com/tree-sitter/tree-sitter/issues/2062

**Comment by fwcd** [comment]
Thanks for the tip!

**Comment by edwardloveall** [comment]
> This worked for me:
> 
> ```
> emsdk install 2.0.17 && emsdk activate 2.0.17
> ```

FWIW, i had to download `2.0.21` instead as `2.0.17 - 2.0.20` were no longer available. For some reason `2.0.30` (the last of the `2.0.x` versions) did not work.

**Comment by VladimirMakaev** [comment]
This is an upstream issue anyway, I'd suggest searching through
https://github.com/tree-sitter/tree-sitter. There may be more discussions
about it
